/**
 * Claims and call-record fields — 06_VOB_FORM_FIELD_ENGINE.md §13 (15 fields).
 *
 * §13 closes with: "Conditional TFL alternatives must retain their conditions
 * rather than being flattened into one number." That is CASE-009 — the corrected
 * claim rule "180 days from DOS or 60 calendar days from RA" must survive intact,
 * so the alternative condition is its own narrative field that cannot auto-pass.
 */

import { VobSection, VobSubgroup } from '../../types/field-keys.js';
import type { FieldOption } from '../../types/field-definition.js';
import {
  CALL_VERIFIABLE_SOURCES,
  MASTER_ELIGIBLE_SOURCES,
  SYSTEM_SOURCES,
  defineField,
  type FieldStructure,
} from '../define.js';

const TFL_UNIT_OPTIONS: readonly FieldOption[] = [
  { value: 'DAYS', label: 'Days' },
  { value: 'MONTHS', label: 'Months' },
  { value: 'YEARS', label: 'Years' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

const TFL_REFERENCE_OPTIONS: readonly FieldOption[] = [
  { value: 'DATE_OF_SERVICE', label: 'From date of service' },
  { value: 'REMITTANCE_ADVICE', label: 'From remittance advice' },
  { value: 'DATE_OF_DISCHARGE', label: 'From date of discharge' },
  { value: 'ORIGINAL_CLAIM_DECISION', label: 'From the original claim decision' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

export const CLAIMS_CALL_FIELDS: readonly FieldStructure[] = [
  defineField({
    key: 'claims.mailingAddress',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Claims mailing address',
    dataType: 'address',
    control: 'address',
    normalization: 'ADDRESS',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Claims address',
    helpText:
      'Where paper claims are sent. Marked reusable in the template, so it normally comes from a scoped carrier master rather than one call (MTG-015).',
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-015', 'CASE-011', 'TPL-025'],
  }),
  defineField({
    key: 'claims.payerId',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Claims payer ID',
    dataType: 'identifier',
    control: 'text',
    normalization: 'IDENTIFIER',
    comparison: 'IDENTIFIER_STRICT',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Claims payer ID',
    helpText:
      'Electronic payer identifier used for claim submission. Kept separate from the eligibility payer ID because they can differ.',
    examples: ['ASHP1'],
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-015', 'TPL-015'],
  }),
  defineField({
    key: 'claims.originalTflValue',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Original claim timely filing',
    dataType: 'integer',
    control: 'number',
    normalization: 'INTEGER',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Original TFL',
    helpText:
      'Filing deadline for a first-time claim. A form value of 90 days against a payer statement of 180 days is a material mismatch, not a formatting difference.',
    examples: ['180'],
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-015', 'CASE-003', 'TPL-026'],
  }),
  defineField({
    key: 'claims.originalTflUnit',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Original TFL unit',
    dataType: 'categorical',
    control: 'select',
    options: TFL_UNIT_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Original TFL unit',
    helpText: 'Days, months or years. 90 days and 3 months are not assumed equivalent.',
    privacy: 'OPERATIONAL',
    traceIds: ['CASE-003', 'TPL-026'],
  }),
  defineField({
    key: 'claims.originalTflReference',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Original TFL measured from',
    dataType: 'categorical',
    control: 'select',
    options: TFL_REFERENCE_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Original TFL from',
    helpText:
      'The reference point the deadline counts from. 180 days from date of service is a different rule from 180 days from discharge.',
    privacy: 'OPERATIONAL',
    traceIds: ['CASE-003', 'TPL-026'],
  }),
  defineField({
    key: 'claims.correctedTflValue',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Corrected claim timely filing',
    dataType: 'integer',
    control: 'number',
    normalization: 'INTEGER',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Corrected TFL',
    helpText:
      'Filing deadline for a corrected or resubmitted claim. Original and corrected claim contexts are distinct and must not be merged (08 §10).',
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-015', 'CASE-009', 'TPL-027'],
  }),
  defineField({
    key: 'claims.correctedTflUnit',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Corrected TFL unit',
    dataType: 'categorical',
    control: 'select',
    options: TFL_UNIT_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Corrected TFL unit',
    helpText: 'Days, months or years for the corrected-claim deadline.',
    privacy: 'OPERATIONAL',
    traceIds: ['CASE-009', 'TPL-027'],
  }),
  defineField({
    key: 'claims.correctedTflReference',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Corrected TFL measured from',
    dataType: 'categorical',
    control: 'select',
    options: TFL_REFERENCE_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Corrected TFL from',
    helpText: 'Reference point for the corrected-claim deadline, such as the remittance advice.',
    privacy: 'OPERATIONAL',
    traceIds: ['CASE-009', 'TPL-027'],
  }),
  defineField({
    key: 'claims.correctedTflAlternativeRule',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CLAIMS,
    label: 'Corrected TFL alternative condition',
    dataType: 'longText',
    control: 'textarea',
    normalization: 'FREE_TEXT',
    comparison: 'NARRATIVE_REVIEW',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Corrected TFL alternative',
    helpText:
      'The conditional alternative stated alongside the primary deadline, kept verbatim. A rule such as "180 days from DOS or 60 calendar days from the remittance advice" must never be flattened into a single number.',
    examples: ['180 days from DOS or 60 calendar days from RA'],
    privacy: 'OPERATIONAL',
    traceIds: ['CASE-009', 'TPL-027'],
  }),
  defineField({
    key: 'call.representativeName',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CALL_RECORD,
    label: 'Representative name',
    dataType: 'text',
    control: 'text',
    normalization: 'STRING',
    comparison: 'NARRATIVE_REVIEW',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Representative',
    helpText:
      'Who provided the information. Speech-to-text frequently garbles names, so an unconfirmed suffix or spelling is surfaced for review rather than accepted as supported.',
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-010', 'CASE-010', 'TPL-028'],
  }),
  defineField({
    key: 'call.referenceNumber',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CALL_RECORD,
    label: 'Call reference number',
    dataType: 'identifier',
    control: 'text',
    normalization: 'IDENTIFIER',
    comparison: 'IDENTIFIER_STRICT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Call reference',
    helpText:
      'The payer-issued confirmation or interaction number for this call. Also used to detect duplicate verification events (10 §2).',
    examples: ['20874738'],
    privacy: 'PHI_INDIRECT',
    traceIds: ['MTG-010', 'TPL-028'],
  }),
  defineField({
    key: 'call.sourcePhone',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CALL_RECORD,
    label: 'Number called',
    dataType: 'phone',
    control: 'phone',
    normalization: 'PHONE',
    comparison: 'EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Number called',
    helpText: 'The payer number dialed for this verification.',
    privacy: 'OPERATIONAL',
    traceIds: ['TPL-028'],
  }),
  defineField({
    key: 'call.startedAt',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CALL_RECORD,
    label: 'Call started',
    dataType: 'dateTime',
    control: 'dateTime',
    normalization: 'DATE_TIME',
    comparison: 'NOT_COMPARED',
    allowedSources: SYSTEM_SOURCES,
    temporalClass: 'system',
    exportColumn: 'Call started',
    helpText:
      'Call start timestamp with timezone. Timezone applies to call times only, never to date-only benefit fields (08 §13).',
    privacy: 'OPERATIONAL',
    traceIds: ['TPL-028'],
  }),
  defineField({
    key: 'call.endedAt',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CALL_RECORD,
    label: 'Call ended',
    dataType: 'dateTime',
    control: 'dateTime',
    normalization: 'DATE_TIME',
    comparison: 'NOT_COMPARED',
    allowedSources: SYSTEM_SOURCES,
    temporalClass: 'system',
    exportColumn: 'Call ended',
    helpText: 'Call end timestamp with timezone.',
    privacy: 'OPERATIONAL',
    traceIds: ['TPL-028'],
  }),
  defineField({
    key: 'call.ringCentralRecordId',
    section: VobSection.CLAIMS_CALL,
    subgroup: VobSubgroup.CALL_RECORD,
    label: 'RingCentral recording ID',
    dataType: 'identifier',
    control: 'readOnly',
    normalization: 'IDENTIFIER',
    comparison: 'NOT_COMPARED',
    allowedSources: SYSTEM_SOURCES,
    temporalClass: 'system',
    exportColumn: 'RingCentral ID',
    helpText:
      'Populated only when a call arrives through the RingCentral adapter. That integration is deferred pending the discovery questions in 12 §13, so this field stays empty for manually uploaded sources.',
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-004', 'ADR-011'],
  }),
];
