/**
 * Financial fields — 06_VOB_FORM_FIELD_ENGINE.md §8 (responsibility, 7),
 * §9 (deductible, 10) and §10 (out of pocket, 9). 26 fields.
 *
 * The load-bearing prohibition lives here. 06 §8:
 *   "financial.coveragePercent must not be auto-derived from No copay and No coinsurance."
 * Reinforced by ADR-012, 08 §15 and 13 §9. `coveragePercent` therefore has NO
 * derivation rule and only accepts an explicitly supported source.
 */

import { VobSection, VobSubgroup } from '../../types/field-keys.js';
import type { FieldOption } from '../../types/field-definition.js';
import { ANSWER_OPTIONS } from '../../types/field-definition.js';
import { rule } from '../../types/rule-expression.js';
import {
  CALL_VERIFIABLE_SOURCES,
  DERIVABLE_SOURCES,
  defineField,
  type FieldStructure,
} from '../define.js';

const SCOPE_OPTIONS: readonly FieldOption[] = [
  { value: 'INDIVIDUAL', label: 'Individual' },
  { value: 'FAMILY', label: 'Family' },
  { value: 'COMBINED', label: 'Combined individual and family' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

const PERIOD_OPTIONS: readonly FieldOption[] = [
  { value: 'CALENDAR_YEAR', label: 'Calendar year' },
  { value: 'BENEFIT_YEAR', label: 'Benefit year' },
  { value: 'ROLLING_PERIOD', label: 'Rolling period' },
  { value: 'LIFETIME', label: 'Lifetime' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

// ---------------------------------------------------------------------------
// §8 Copay, coinsurance and patient responsibility
// ---------------------------------------------------------------------------

const RESPONSIBILITY_FIELDS: readonly FieldStructure[] = [
  defineField({
    key: 'financial.copayApplies',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.RESPONSIBILITY,
    label: 'Copay applies',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Copay applies',
    helpText:
      'Whether a per-visit copay applies. A blank answer is never read as No — silence and absence are not verified negatives (08 §8).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CUR-004', 'TPL-016'],
  }),
  defineField({
    key: 'financial.copayAmount',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.RESPONSIBILITY,
    label: 'Copay amount',
    dataType: 'money',
    control: 'money',
    // 06 §17: "When copayApplies is YES, copayAmount becomes required."
    visibleRule: rule.neq('financial.copayApplies', 'NOT_APPLICABLE'),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Copay amount',
    helpText:
      'Per-visit copay in dollars. $20, $20.00 and "twenty dollars" are the same value; amounts are stored in integer cents, never floating point.',
    examples: ['$20', 'twenty dollars'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-016'],
  }),
  defineField({
    key: 'financial.coinsuranceApplies',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.RESPONSIBILITY,
    label: 'Coinsurance applies',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Coinsurance applies',
    helpText: 'Whether percentage cost sharing applies. Blank is never read as No.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CUR-004', 'TPL-017'],
  }),
  defineField({
    key: 'financial.patientCoinsurancePercent',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.RESPONSIBILITY,
    label: 'Patient coinsurance',
    documentLabel: 'Coinsurance',
    dataType: 'percent',
    control: 'percent',
    visibleRule: rule.neq('financial.coinsuranceApplies', 'NOT_APPLICABLE'),
    normalization: 'PERCENT',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Patient coinsurance %',
    helpText:
      'The percentage the patient owes. This is not the same label as payer coverage: 20% patient responsibility and 80% payer coverage are related but distinct fields (08 §15).',
    examples: ['20%'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CASE-002', 'TPL-017'],
  }),
  defineField({
    key: 'financial.payerCoveragePercent',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.RESPONSIBILITY,
    label: 'Payer coverage',
    dataType: 'percent',
    control: 'percent',
    normalization: 'PERCENT',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    // 06 §8: only "when explicitly supported". No derivation rule is attached.
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Payer coverage %',
    helpText:
      'The percentage the payer pays, recorded only when a source explicitly states it. It is never inferred from the patient coinsurance and never assumed to be 100%.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['ADR-012', 'TPL-017'],
  }),
  defineField({
    key: 'financial.coveragePercent',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.RESPONSIBILITY,
    label: 'Coverage percentage',
    dataType: 'percent',
    control: 'percent',
    normalization: 'PERCENT',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Coverage %',
    helpText:
      'Legacy coverage percentage carried forward from the current form. It has no derivation rule by design: no copay plus no coinsurance does not prove 100% coverage, because deductible, exclusions, authorization or visit limits may still apply.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['ADR-012', 'CUR-007', 'TPL-012'],
  }),
  defineField({
    key: 'financial.patientResponsibilitySummary',
    section: VobSection.SUMMARY,
    subgroup: VobSubgroup.ROLLUP,
    label: 'Patient responsibility',
    dataType: 'longText',
    control: 'textarea',
    normalization: 'FREE_TEXT',
    comparison: 'NARRATIVE_REVIEW',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'derived',
    exportColumn: 'Patient responsibility',
    helpText:
      'The responsibility banner shown on the report. Built only from explicitly supported or approved derived facts, and marked reviewable when its source facts conflict (13 §9).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['ADR-012', 'TPL-004'],
  }),
];

// ---------------------------------------------------------------------------
// §9 Deductible
//
// "Met and remaining values are dynamic and require dated provenance."
// "Arithmetic consistency may raise review but must not silently replace
//  transcript evidence." — so no deductible field derives by default.
// ---------------------------------------------------------------------------

const DEDUCTIBLE_FIELDS: readonly FieldStructure[] = [
  defineField({
    key: 'financial.deductibleApplies',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Deductible applies',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Deductible applies',
    helpText: 'Whether a deductible must be satisfied. Blank is never read as No.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CUR-004', 'TPL-018'],
  }),
  defineField({
    key: 'financial.deductibleScope',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Deductible scope',
    dataType: 'categorical',
    control: 'select',
    options: SCOPE_OPTIONS,
    visibleRule: rule.neq('financial.deductibleApplies', 'NOT_APPLICABLE'),
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Deductible scope',
    helpText:
      'Individual, family or combined. An individual figure and a family figure are different values, not a contradiction (08 §10).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-018'],
  }),
  defineField({
    key: 'financial.individualDeductibleTotal',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Individual deductible',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.neq('financial.deductibleApplies', 'NOT_APPLICABLE'),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Individual deductible',
    helpText: 'Total individual deductible for the period.',
    examples: ['$3,000.00'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-018'],
  }),
  defineField({
    key: 'financial.individualDeductibleMet',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Individual deductible met',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.neq('financial.deductibleApplies', 'NOT_APPLICABLE'),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Individual deductible met',
    helpText:
      'Amount accumulated to date. Requires an as-of date. When the call audio is garbled, competing candidates are retained rather than forced into one clean value (CASE-008).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-013', 'CASE-008', 'TPL-018'],
  }),
  defineField({
    key: 'financial.individualDeductibleRemaining',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Individual deductible remaining',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.neq('financial.deductibleApplies', 'NOT_APPLICABLE'),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Individual deductible remaining',
    helpText:
      'Balance still owed. Arithmetic consistency against total and met raises review; it never silently overwrites what the representative said.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-013', 'CASE-008', 'TPL-018'],
  }),
  defineField({
    key: 'financial.familyDeductibleTotal',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Family deductible',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.oneOf('financial.deductibleScope', ['FAMILY', 'COMBINED']),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Family deductible',
    helpText: 'Total family deductible, captured when the client requests family accumulators.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-018'],
  }),
  defineField({
    key: 'financial.familyDeductibleMet',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Family deductible met',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.oneOf('financial.deductibleScope', ['FAMILY', 'COMBINED']),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Family deductible met',
    helpText: 'Family amount accumulated to date. Requires an as-of date.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-018'],
  }),
  defineField({
    key: 'financial.familyDeductibleRemaining',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Family deductible remaining',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.oneOf('financial.deductibleScope', ['FAMILY', 'COMBINED']),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Family deductible remaining',
    helpText: 'Family balance still owed.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-018'],
  }),
  defineField({
    key: 'financial.deductiblePeriod',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Deductible period',
    dataType: 'categorical',
    control: 'select',
    options: PERIOD_OPTIONS,
    visibleRule: rule.neq('financial.deductibleApplies', 'NOT_APPLICABLE'),
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Deductible period',
    helpText:
      'Calendar year, benefit year or another period. Accumulators from different periods are not compared as one value.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-018'],
  }),
  defineField({
    key: 'financial.deductibleAsOfDate',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.DEDUCTIBLE,
    label: 'Deductible as of',
    dataType: 'date',
    control: 'date',
    visibleRule: rule.neq('financial.deductibleApplies', 'NOT_APPLICABLE'),
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Deductible as of',
    helpText:
      'The date the met and remaining figures were accurate. Every dynamic value carries an as-of date (10 §6).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-014', 'MTG-017'],
  }),
];

// ---------------------------------------------------------------------------
// §10 Out of pocket
//
// "OOP met may be derived from maximum minus remaining only when both operands
//  are clear and the rule is enabled." — CASE-007.
// "Derived values remain visibly labeled."
// ---------------------------------------------------------------------------

const OOP_FIELDS: readonly FieldStructure[] = [
  defineField({
    key: 'financial.oopScope',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Out-of-pocket scope',
    dataType: 'categorical',
    control: 'select',
    options: SCOPE_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'OOP scope',
    helpText: 'Individual, family or combined out-of-pocket accumulator.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-019'],
  }),
  defineField({
    key: 'financial.individualOopMaximum',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Individual out-of-pocket maximum',
    documentLabel: 'OOP max',
    dataType: 'money',
    control: 'money',
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Individual OOP maximum',
    helpText: 'Maximum the patient can owe in the period.',
    examples: ['$6,500.00'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-019'],
  }),
  defineField({
    key: 'financial.individualOopMet',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Individual out-of-pocket met',
    dataType: 'money',
    control: 'money',
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: DERIVABLE_SOURCES,
    temporalClass: 'derived',
    derivation: {
      id: 'DERIVE-OOP-MET-V1',
      operands: ['financial.individualOopMaximum', 'financial.individualOopRemaining'],
      kind: 'SUBTRACT',
      describe: (labels) => `${labels[0] ?? 'maximum'} − ${labels[1] ?? 'remaining'}`,
      enabledByDefault: true,
    },
    exportColumn: 'Individual OOP met',
    helpText:
      'Amount accumulated to date. May be calculated as maximum minus remaining when both operands are clear; the result is labeled Derived and shows its formula, never Match.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['CASE-007', 'MTG-013', 'TPL-019'],
  }),
  defineField({
    key: 'financial.individualOopRemaining',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Individual out-of-pocket remaining',
    dataType: 'money',
    control: 'money',
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Individual OOP remaining',
    helpText: 'Amount the patient could still owe before the maximum is reached.',
    examples: ['$5,473.76'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-013', 'TPL-019'],
  }),
  defineField({
    key: 'financial.familyOopMaximum',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Family out-of-pocket maximum',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.oneOf('financial.oopScope', ['FAMILY', 'COMBINED']),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Family OOP maximum',
    helpText: 'Family out-of-pocket maximum, captured when requested.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-019'],
  }),
  defineField({
    key: 'financial.familyOopMet',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Family out-of-pocket met',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.oneOf('financial.oopScope', ['FAMILY', 'COMBINED']),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: DERIVABLE_SOURCES,
    temporalClass: 'derived',
    derivation: {
      id: 'DERIVE-FAMILY-OOP-MET-V1',
      operands: ['financial.familyOopMaximum', 'financial.familyOopRemaining'],
      kind: 'SUBTRACT',
      describe: (labels) => `${labels[0] ?? 'maximum'} − ${labels[1] ?? 'remaining'}`,
      enabledByDefault: false,
    },
    exportColumn: 'Family OOP met',
    helpText: 'Family amount accumulated to date.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-019'],
  }),
  defineField({
    key: 'financial.familyOopRemaining',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Family out-of-pocket remaining',
    dataType: 'money',
    control: 'money',
    visibleRule: rule.oneOf('financial.oopScope', ['FAMILY', 'COMBINED']),
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Family OOP remaining',
    helpText: 'Family balance before the maximum is reached.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-019'],
  }),
  defineField({
    key: 'financial.oopPeriod',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Out-of-pocket period',
    dataType: 'categorical',
    control: 'select',
    options: PERIOD_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'OOP period',
    helpText: 'The period the out-of-pocket accumulator covers.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-019'],
  }),
  defineField({
    key: 'financial.oopAsOfDate',
    section: VobSection.FINANCIALS,
    subgroup: VobSubgroup.OUT_OF_POCKET,
    label: 'Out-of-pocket as of',
    dataType: 'date',
    control: 'date',
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'OOP as of',
    helpText: 'The date the out-of-pocket figures were accurate.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-014', 'MTG-017'],
  }),
];

export const FINANCIAL_FIELDS: readonly FieldStructure[] = [
  ...RESPONSIBILITY_FIELDS,
  ...DEDUCTIBLE_FIELDS,
  ...OOP_FIELDS,
];
