/**
 * Primary insurance and plan fields — 06_VOB_FORM_FIELD_ENGINE.md §7 (17 fields).
 *
 * §7 closes with the required structural change: "The current single network field
 * must be split because the template distinguishes group and individual-provider
 * status." Both fields exist here, and neither defaults to In Network (06 §18).
 */

import { VobSection, VobSubgroup } from '../../types/field-keys.js';
import type { FieldOption } from '../../types/field-definition.js';
import {
  CALL_VERIFIABLE_SOURCES,
  IDENTITY_SOURCES,
  MASTER_ELIGIBLE_SOURCES,
  defineField,
  type FieldStructure,
} from '../define.js';

/**
 * Network options. 06 §18: "Do not default network to In Network."
 * There is no pre-selected option — the control starts unselected.
 */
const NETWORK_OPTIONS: readonly FieldOption[] = [
  { value: 'IN_NETWORK', label: 'In network' },
  { value: 'OUT_OF_NETWORK', label: 'Out of network' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
  { value: 'NOT_APPLICABLE', label: 'Not applicable', isUnknownFamily: true },
];

/** 06 §18: "Do not default service type to PT unless inherited from a selected source." */
const SERVICE_TYPE_OPTIONS: readonly FieldOption[] = [
  { value: 'PT', label: 'Physical therapy (PT)' },
  { value: 'OT', label: 'Occupational therapy (OT)' },
  { value: 'ST', label: 'Speech therapy (ST)' },
  { value: 'CHIROPRACTIC', label: 'Chiropractic' },
  { value: 'COMBINED', label: 'Combined therapies' },
  { value: 'OTHER', label: 'Other' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

const LINE_OF_BUSINESS_OPTIONS: readonly FieldOption[] = [
  { value: 'COMMERCIAL', label: 'Commercial' },
  { value: 'MEDICARE', label: 'Medicare' },
  { value: 'MEDICARE_ADVANTAGE', label: 'Medicare Advantage' },
  { value: 'MEDICAID', label: 'Medicaid' },
  { value: 'MARKETPLACE', label: 'Marketplace / exchange' },
  { value: 'OTHER', label: 'Other' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

const PLAN_TYPE_OPTIONS: readonly FieldOption[] = [
  { value: 'HMO', label: 'HMO' },
  { value: 'PPO', label: 'PPO' },
  { value: 'EPO', label: 'EPO' },
  { value: 'POS', label: 'POS' },
  { value: 'INDEMNITY', label: 'Indemnity' },
  { value: 'OTHER', label: 'Other' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

/** 08 §13: `current` is an eligibility concept, never a fake termination date. */
const ELIGIBILITY_OPTIONS: readonly FieldOption[] = [
  { value: 'ACTIVE', label: 'Active' },
  { value: 'TERMINATED', label: 'Terminated' },
  { value: 'PENDING', label: 'Pending' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

export const INSURANCE_FIELDS: readonly FieldStructure[] = [
  defineField({
    key: 'primary.insuranceName',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.IDENTITY,
    label: 'Insurance name',
    dataType: 'text',
    control: 'text',
    normalization: 'STRING',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Insurance',
    helpText:
      'Payer or administrator name. The filename is never evidence for this field — CASE-012 covers a file named UHC whose content concerns Cigna ASH.',
    examples: ['Cigna ASH'],
    privacy: 'PHI_INDIRECT',
    traceIds: ['MTG-007', 'CASE-012', 'TPL-005'],
  }),
  defineField({
    key: 'primary.insurancePhone',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.IDENTITY,
    label: 'Insurance phone',
    dataType: 'phone',
    control: 'phone',
    normalization: 'PHONE',
    comparison: 'EXACT',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Insurance phone',
    helpText:
      'Benefits or customer-service number. Typically supplied by a scoped carrier master rather than restated on every call (CASE-011, MTG-015).',
    examples: ['800-972-4226'],
    privacy: 'OPERATIONAL',
    traceIds: ['CASE-011', 'MTG-015', 'TPL-006'],
  }),
  defineField({
    key: 'primary.policyId',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.IDENTITY,
    label: 'Policy ID',
    documentLabel: 'Policy #',
    dataType: 'identifier',
    control: 'text',
    normalization: 'IDENTIFIER',
    comparison: 'IDENTIFIER_STRICT',
    allowedSources: IDENTITY_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Policy ID',
    helpText:
      'Member or subscriber identifier. Leading zeros and alpha affixes are preserved. A suffix such as -01 is a different identifier unless a payer-approved rule relates them (CASE-006).',
    examples: ['106723434', '106723434-01'],
    privacy: 'PHI_INDIRECT',
    traceIds: ['MTG-007', 'CASE-006', 'TPL-007'],
  }),
  defineField({
    key: 'primary.groupId',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.IDENTITY,
    label: 'Group ID',
    documentLabel: 'Group #',
    dataType: 'identifier',
    control: 'text',
    normalization: 'IDENTIFIER',
    comparison: 'IDENTIFIER_STRICT',
    allowedSources: IDENTITY_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Group ID',
    helpText:
      'Employer or group identifier. Leading zeros are significant and are preserved everywhere including Excel export.',
    examples: ['00633434'],
    privacy: 'PHI_INDIRECT',
    traceIds: ['MTG-007', 'TPL-008'],
  }),
  defineField({
    key: 'primary.planName',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.PLAN,
    label: 'Plan name',
    dataType: 'text',
    control: 'text',
    normalization: 'STRING',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Plan name',
    helpText: 'Product or plan name as the payer states it.',
    privacy: 'PHI_INDIRECT',
    traceIds: ['CASE-011', 'TPL-009'],
  }),
  defineField({
    key: 'primary.planType',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.PLAN,
    label: 'Plan type',
    dataType: 'categorical',
    control: 'select',
    options: PLAN_TYPE_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Plan type',
    helpText: 'Benefit structure such as HMO or PPO. Requires a source; it is never inferred.',
    privacy: 'PHI_INDIRECT',
    traceIds: ['CASE-011', 'TPL-009'],
  }),
  defineField({
    key: 'primary.lineOfBusiness',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.PLAN,
    label: 'Line of business',
    dataType: 'categorical',
    control: 'select',
    options: LINE_OF_BUSINESS_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Line of business',
    helpText:
      'Commercial, Medicare, Medicaid and similar. Also a carrier-master scope dimension (10 §13).',
    privacy: 'OPERATIONAL',
    traceIds: ['ENG-010', 'TPL-009'],
  }),
  defineField({
    key: 'primary.serviceType',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.PLAN,
    label: 'Service type',
    dataType: 'categorical',
    control: 'select',
    options: SERVICE_TYPE_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: IDENTITY_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Service',
    helpText:
      'The therapy or service being verified. Never defaulted to PT — benefits frequently differ by service, so an unselected value stays unselected.',
    examples: ['PT'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-010'],
  }),
  defineField({
    key: 'primary.networkGroupStatus',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.NETWORK,
    label: 'Network status — group',
    documentLabel: 'Network (group)',
    dataType: 'categorical',
    control: 'select',
    options: NETWORK_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Network (group)',
    helpText:
      'Whether the billing group is contracted. The marked template distinguishes this from the individual provider, so the two are separate fields.',
    examples: ['In network', 'INN'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-007', 'MTG-010', 'CUR-013', 'TPL-011'],
  }),
  defineField({
    key: 'primary.networkIndividualProviderStatus',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.NETWORK,
    label: 'Network status — individual provider',
    documentLabel: 'Network (provider)',
    dataType: 'categorical',
    control: 'select',
    options: NETWORK_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Network (provider)',
    helpText:
      'Whether the treating provider is individually contracted. A contracted group does not prove an individually contracted provider.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CUR-013', 'TPL-011'],
  }),
  defineField({
    key: 'primary.coverageSummary',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.ELIGIBILITY,
    label: 'Coverage summary',
    dataType: 'longText',
    control: 'textarea',
    normalization: 'FREE_TEXT',
    comparison: 'NARRATIVE_REVIEW',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Coverage',
    helpText:
      'Narrative coverage description. Differences route to review rather than being judged a match on fuzzy similarity, and a claim such as "100% covered" is never generated here.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-007', 'ADR-012', 'TPL-012'],
  }),
  defineField({
    key: 'primary.effectiveDate',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.ELIGIBILITY,
    label: 'Effective date',
    dataType: 'date',
    control: 'date',
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Effective date',
    helpText: 'Date coverage began. Kept separate from the termination date.',
    examples: ['10/01/2025'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-007', 'MTG-010', 'TPL-013'],
  }),
  defineField({
    key: 'primary.terminationDate',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.ELIGIBILITY,
    label: 'Termination date',
    dataType: 'date',
    control: 'date',
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Termination date',
    helpText:
      'An explicit coverage end date. "No termination date is listed" is not the literal value No and is not a date — leave this blank and record eligibility as Active instead.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CUR-005', 'TPL-013'],
  }),
  defineField({
    key: 'primary.eligibilityStatus',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.ELIGIBILITY,
    label: 'Eligibility status',
    dataType: 'categorical',
    control: 'select',
    options: ELIGIBILITY_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Eligibility',
    helpText:
      'Whether coverage is active as of the verification date. "Current" is represented here as Active with an open-ended period, never as an invented termination date.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-013'],
  }),
  defineField({
    key: 'primary.hsaHraHcaAmount',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.PLAN,
    label: 'HSA / HRA / HCA amount',
    dataType: 'money',
    control: 'money',
    normalization: 'MONEY',
    comparison: 'MONEY_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'HSA/HRA/HCA',
    helpText:
      'Account balance or allowance where the payer reports one. The exact business use of these three account types remains configurable (00 §10).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-014'],
  }),
  defineField({
    key: 'primary.payerId',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.IDENTITY,
    label: 'Payer ID',
    dataType: 'identifier',
    control: 'text',
    normalization: 'IDENTIFIER',
    comparison: 'IDENTIFIER_STRICT',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Payer ID',
    helpText:
      'Electronic payer identifier. Marked "one time" in the template, so it is normally supplied by a scoped carrier master (MTG-015).',
    examples: ['ASHP1'],
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-015', 'CASE-011', 'TPL-015'],
  }),
  defineField({
    key: 'primary.stateOrMarket',
    section: VobSection.INSURANCE,
    subgroup: VobSubgroup.PLAN,
    label: 'State or market',
    dataType: 'text',
    control: 'text',
    normalization: 'STRING',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'State / market',
    helpText:
      'Required to scope carrier-master lookups. A master lacking the scope dimensions cannot auto-fill a critical field (10 §13).',
    privacy: 'OPERATIONAL',
    traceIds: ['ENG-011'],
  }),
];
