/**
 * Patient and verification fields — 06_VOB_FORM_FIELD_ENGINE.md §6 (12 fields).
 *
 * §6 closes with: "These fields distinguish patient identity from operator and
 * system metadata." The operator label in particular is operational metadata and
 * must never be presented as strong authentication (09 §14).
 */

import { VobSection, VobSubgroup } from '../../types/field-keys.js';
import { defineField, IDENTITY_SOURCES, SYSTEM_SOURCES, type FieldStructure } from '../define.js';

export const PATIENT_FIELDS: readonly FieldStructure[] = [
  defineField({
    key: 'patient.lastName',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.IDENTITY,
    label: 'Last name',
    dataType: 'text',
    control: 'text',
    normalization: 'STRING',
    comparison: 'ALIAS',
    allowedSources: IDENTITY_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Patient last name',
    helpText:
      'Family name as held by the payer. Speech-to-text often misspells names, so a difference from the call is surfaced for review rather than auto-corrected.',
    examples: ['Carsten'],
    privacy: 'PHI_DIRECT',
    traceIds: ['MTG-007', 'TPL-001'],
  }),
  defineField({
    key: 'patient.firstName',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.IDENTITY,
    label: 'First name',
    dataType: 'text',
    control: 'text',
    normalization: 'STRING',
    comparison: 'ALIAS',
    allowedSources: IDENTITY_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Patient first name',
    helpText: 'Given name as held by the payer.',
    privacy: 'PHI_DIRECT',
    traceIds: ['MTG-007', 'TPL-001'],
  }),
  defineField({
    key: 'patient.middleName',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.IDENTITY,
    label: 'Middle name',
    dataType: 'text',
    control: 'text',
    normalization: 'STRING',
    comparison: 'ALIAS',
    allowedSources: IDENTITY_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Patient middle name',
    helpText:
      'Optional. Present in the registry because 06 §6 anticipates the client requiring it later; it carries no requirement until the field matrix is approved.',
    privacy: 'PHI_DIRECT',
    traceIds: ['TPL-001'],
  }),
  defineField({
    key: 'patient.dateOfBirth',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.IDENTITY,
    label: 'Date of birth',
    documentLabel: 'DOB',
    dataType: 'date',
    control: 'date',
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: IDENTITY_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'DOB',
    helpText:
      'Stored as an ISO date and displayed in US format. Spoken forms such as "October 7th 2010" normalize to the same value as 10/07/2010. Ambiguous numeric dates are never disambiguated by guessing.',
    examples: ['10/07/2010', 'October 7th 2010'],
    privacy: 'PHI_DIRECT',
    traceIds: ['MTG-007', 'CASE-001', 'TPL-001'],
  }),
  defineField({
    key: 'verification.date',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.VERIFICATION_META,
    label: 'Verification date',
    dataType: 'date',
    control: 'date',
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: ['MANUAL_ENTRY', 'IMPORTED_COMPLETED_FORM', 'MANUAL_CORRECTION', 'UNKNOWN'],
    temporalClass: 'system',
    exportColumn: 'Verification date',
    helpText:
      'The date this verification was performed. Dated accumulator values on the report are read as of this date (13 §10).',
    privacy: 'PHI_INDIRECT',
    traceIds: ['MTG-014', 'TPL-002'],
  }),
  defineField({
    key: 'verification.time',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.VERIFICATION_META,
    label: 'Verification time',
    dataType: 'dateTime',
    control: 'dateTime',
    normalization: 'DATE_TIME',
    comparison: 'NOT_COMPARED',
    allowedSources: SYSTEM_SOURCES,
    temporalClass: 'system',
    exportColumn: 'Verification time',
    helpText: 'Optional call time, recorded when operationally useful.',
    privacy: 'PHI_INDIRECT',
    traceIds: ['TPL-002'],
  }),
  defineField({
    key: 'verification.verifiedByLabel',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.VERIFICATION_META,
    label: 'Verified by',
    dataType: 'text',
    control: 'text',
    normalization: 'STRING',
    comparison: 'NOT_COMPARED',
    allowedSources: SYSTEM_SOURCES,
    temporalClass: 'system',
    exportColumn: 'Verified by',
    helpText:
      'Operational metadata only. Because version one has no login (ADR-008), this label is not proof of identity and must not be presented as non-repudiation.',
    privacy: 'OPERATIONAL',
    traceIds: ['CLT-011', 'SEC-004'],
  }),
  defineField({
    key: 'verification.caseId',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.VERIFICATION_META,
    label: 'Case ID',
    dataType: 'identifier',
    control: 'readOnly',
    normalization: 'IDENTIFIER',
    comparison: 'NOT_COMPARED',
    allowedSources: SYSTEM_SOURCES,
    temporalClass: 'system',
    exportColumn: 'Case ID',
    helpText: 'System-generated case identifier.',
    privacy: 'SYSTEM',
    traceIds: ['ENG-001'],
  }),
  defineField({
    key: 'verification.baseRecordId',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.VERIFICATION_META,
    label: 'Base record ID',
    dataType: 'identifier',
    control: 'readOnly',
    normalization: 'IDENTIFIER',
    comparison: 'NOT_COMPARED',
    allowedSources: SYSTEM_SOURCES,
    temporalClass: 'system',
    exportColumn: 'Base record ID',
    helpText:
      'The patient-policy-service grouping that owns this and every later dated verification (MTG-012).',
    privacy: 'SYSTEM',
    traceIds: ['MTG-012', 'ENG-002'],
  }),
  defineField({
    key: 'verification.versionNumber',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.VERIFICATION_META,
    label: 'Version number',
    dataType: 'integer',
    control: 'readOnly',
    normalization: 'INTEGER',
    comparison: 'NOT_COMPARED',
    allowedSources: SYSTEM_SOURCES,
    temporalClass: 'system',
    exportColumn: 'Version',
    helpText: 'Sequential verification version under the base record. Version one is the first VOB.',
    privacy: 'SYSTEM',
    traceIds: ['MTG-012', 'MTG-013'],
  }),
  defineField({
    key: 'verification.serviceDate',
    section: VobSection.PATIENT,
    subgroup: VobSubgroup.VERIFICATION_META,
    label: 'Date of service',
    documentLabel: 'DOS',
    dataType: 'date',
    control: 'date',
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: IDENTITY_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Date of service',
    helpText:
      'Requested date of service when supplied. Timely-filing windows are expressed relative to this date.',
    privacy: 'PHI_INDIRECT',
    traceIds: ['TPL-003'],
  }),
  // Free-text roll-up lives in the Summary section of the navigator (05 §8).
  defineField({
    key: 'verification.notes',
    section: VobSection.SUMMARY,
    subgroup: VobSubgroup.ROLLUP,
    label: 'Additional information',
    dataType: 'longText',
    control: 'textarea',
    normalization: 'FREE_TEXT',
    comparison: 'NARRATIVE_REVIEW',
    allowedSources: ['MANUAL_ENTRY', 'IMPORTED_COMPLETED_FORM', 'MANUAL_CORRECTION', 'UNKNOWN'],
    temporalClass: 'stable',
    exportColumn: 'Additional information',
    helpText:
      'Free-text note kept separate from structured facts. Validated so it does not contradict canonical fields (13 §9).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-004'],
  }),
];
