/**
 * Visit and authorization fields — 06_VOB_FORM_FIELD_ENGINE.md §11 (visits, 8)
 * and §12 (authorization and referral, 15). 23 fields.
 *
 * Two spec requirements are structural here:
 *  - §11: "One used out of twenty is a valid derivation from nineteen remaining
 *    when the rule is enabled and evidence is clear." (CASE-004)
 *  - §12: "The threshold is a separate structured value and must not be embedded
 *    only in a coverage sentence." (CASE-001 — the 5th-vs-8th visit mismatch)
 */

import { VobSection, VobSubgroup } from '../../types/field-keys.js';
import type { FieldOption } from '../../types/field-definition.js';
import { ANSWER_OPTIONS } from '../../types/field-definition.js';
import { rule } from '../../types/rule-expression.js';
import {
  CALL_VERIFIABLE_SOURCES,
  DERIVABLE_SOURCES,
  MASTER_ELIGIBLE_SOURCES,
  defineField,
  type FieldStructure,
} from '../define.js';

const VISIT_LIMIT_TYPE_OPTIONS: readonly FieldOption[] = [
  { value: 'HARD_MAXIMUM', label: 'Hard maximum' },
  { value: 'MEDICALLY_NECESSARY', label: 'Medically necessary' },
  { value: 'NO_STATED_LIMIT', label: 'No stated limit' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

const VISIT_PERIOD_OPTIONS: readonly FieldOption[] = [
  { value: 'CALENDAR_YEAR', label: 'Calendar year' },
  { value: 'BENEFIT_YEAR', label: 'Benefit year' },
  { value: 'ROLLING_PERIOD', label: 'Rolling period' },
  { value: 'EPISODE', label: 'Per episode' },
  { value: 'LIFETIME', label: 'Lifetime' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

const AUTH_METHOD_OPTIONS: readonly FieldOption[] = [
  { value: 'PHONE', label: 'By phone' },
  { value: 'PORTAL', label: 'Through a portal' },
  { value: 'FAX', label: 'By fax' },
  { value: 'NOT_REQUIRED', label: 'Not required' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

const WINDOW_UNIT_OPTIONS: readonly FieldOption[] = [
  { value: 'DAYS', label: 'Calendar days' },
  { value: 'BUSINESS_DAYS', label: 'Business days' },
  { value: 'MONTHS', label: 'Months' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

const WINDOW_REFERENCE_OPTIONS: readonly FieldOption[] = [
  { value: 'DATE_OF_SERVICE', label: 'From date of service' },
  { value: 'BEFORE_DATE_OF_SERVICE', label: 'Before date of service' },
  { value: 'FIRST_VISIT', label: 'From the first visit' },
  { value: 'UNKNOWN', label: 'Unknown', isUnknownFamily: true },
];

// ---------------------------------------------------------------------------
// §11 Visits
// ---------------------------------------------------------------------------

const VISIT_FIELDS: readonly FieldStructure[] = [
  defineField({
    key: 'visits.limitType',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.VISITS,
    label: 'Visit limit type',
    dataType: 'categorical',
    control: 'select',
    options: VISIT_LIMIT_TYPE_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Visit limit type',
    helpText:
      'A hard maximum, a medically-necessary determination, or no stated limit. "Medically necessary" is a limit type, not an unlimited benefit.',
    examples: ['hard max', '20 visits per calendar year'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-020'],
  }),
  defineField({
    key: 'visits.allowedCount',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.VISITS,
    label: 'Visits allowed',
    dataType: 'integer',
    control: 'number',
    // 06 §17: "When visit limit type is hard maximum, allowed count becomes required."
    visibleRule: rule.neq('visits.limitType', 'NO_STATED_LIMIT'),
    normalization: 'INTEGER',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Visits allowed',
    helpText: 'Total visits permitted in the period.',
    examples: ['20'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CASE-004', 'TPL-020'],
  }),
  defineField({
    key: 'visits.usedCount',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.VISITS,
    label: 'Visits used',
    dataType: 'integer',
    control: 'number',
    visibleRule: rule.neq('visits.limitType', 'NO_STATED_LIMIT'),
    normalization: 'INTEGER',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: DERIVABLE_SOURCES,
    temporalClass: 'derived',
    derivation: {
      id: 'DERIVE-VISITS-USED-V1',
      operands: ['visits.allowedCount', 'visits.remainingCount'],
      kind: 'SUBTRACT',
      describe: (labels) => `${labels[0] ?? 'allowed'} − ${labels[1] ?? 'remaining'}`,
      enabledByDefault: true,
    },
    exportColumn: 'Visits used',
    helpText:
      'Visits already used. May be derived as allowed minus remaining when both operands are clear — one used follows from twenty allowed and nineteen remaining. Corrections during the call are preserved as a chain, so an earlier "none used" stays visible in evidence.',
    examples: ['1'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['CASE-004', 'MTG-013', 'TPL-020'],
  }),
  defineField({
    key: 'visits.remainingCount',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.VISITS,
    label: 'Visits remaining',
    dataType: 'integer',
    control: 'number',
    visibleRule: rule.neq('visits.limitType', 'NO_STATED_LIMIT'),
    normalization: 'INTEGER',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Visits remaining',
    helpText:
      'Visits still available. The current form has no structured remaining-visits field; this one carries source provenance (02 §3).',
    examples: ['19'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['CASE-004', 'CUR-015', 'TPL-020'],
  }),
  defineField({
    key: 'visits.period',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.VISITS,
    label: 'Visit period',
    dataType: 'categorical',
    control: 'select',
    options: VISIT_PERIOD_OPTIONS,
    visibleRule: rule.neq('visits.limitType', 'NO_STATED_LIMIT'),
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Visit period',
    helpText: 'Calendar year, benefit year, rolling period or episode.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-020'],
  }),
  defineField({
    key: 'visits.combinedServices',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.VISITS,
    label: 'Limit shared across services',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    visibleRule: rule.neq('visits.limitType', 'NO_STATED_LIMIT'),
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Combined service limit',
    helpText:
      'Whether PT, OT and ST draw on one shared allowance. A shared limit materially changes the remaining count for each service.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-020'],
  }),
  defineField({
    key: 'visits.serviceScope',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.VISITS,
    label: 'Visit limit applies to',
    dataType: 'text',
    control: 'text',
    visibleRule: rule.neq('visits.limitType', 'NO_STATED_LIMIT'),
    normalization: 'STRING',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Visit limit scope',
    helpText:
      'The service the count refers to. A count stated for chiropractic is not evidence for physical therapy (08 §10).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-020'],
  }),
  defineField({
    key: 'visits.asOfDate',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.VISITS,
    label: 'Visit counts as of',
    dataType: 'date',
    control: 'date',
    visibleRule: rule.neq('visits.limitType', 'NO_STATED_LIMIT'),
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Visits as of',
    helpText: 'The date the used and remaining counts were accurate.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-014'],
  }),
];

// ---------------------------------------------------------------------------
// §12 Authorization and referral
// ---------------------------------------------------------------------------

const AUTHORIZATION_FIELDS: readonly FieldStructure[] = [
  defineField({
    key: 'authorization.initialEvaluationRequired',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Authorization required for initial evaluation',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Auth required (initial eval)',
    helpText:
      'The template asks about the initial evaluation and ongoing treatment separately, so these are two fields. Never defaulted to Yes or No.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CUR-004', 'TPL-021'],
  }),
  defineField({
    key: 'authorization.treatmentRequired',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Authorization required for treatment',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Auth required (treatment)',
    helpText: 'Whether continued treatment needs authorization.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-021'],
  }),
  defineField({
    key: 'authorization.requiredAfterVisitNumber',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Authorization required after visit number',
    dataType: 'integer',
    control: 'number',
    // 06 §17: "When treatmentRequired is YES, authorization method and threshold
    // may become required." Visibility stays open so the field is never hidden
    // while its answer is unknown (05 §8).
    normalization: 'INTEGER',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Auth after visit #',
    helpText:
      'The visit number after which authorization is needed. Held as a structured number rather than buried in a coverage sentence, so "after the fifth visit" and "after the eighth visit" compare as a real mismatch.',
    examples: ['8', 'after the eighth visit'],
    privacy: 'PHI_BENEFIT',
    traceIds: ['CASE-001', 'CUR-014', 'TPL-021'],
  }),
  defineField({
    key: 'authorization.method',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'How to obtain authorization',
    dataType: 'categorical',
    control: 'select',
    options: AUTH_METHOD_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Auth method',
    helpText:
      'Phone, portal or fax. Often supplied by a scoped carrier master rather than restated on each call.',
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-015', 'TPL-022'],
  }),
  defineField({
    key: 'authorization.phone',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Authorization phone',
    dataType: 'phone',
    control: 'phone',
    visibleRule: rule.neq('authorization.method', 'PORTAL'),
    normalization: 'PHONE',
    comparison: 'EXACT',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Auth phone',
    helpText: 'Number used to request authorization.',
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-015', 'TPL-022'],
  }),
  defineField({
    key: 'authorization.portal',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Authorization portal',
    dataType: 'text',
    control: 'text',
    visibleRule: rule.neq('authorization.method', 'PHONE'),
    normalization: 'STRING',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Auth portal',
    helpText: 'Portal name or address used to request authorization.',
    privacy: 'OPERATIONAL',
    traceIds: ['MTG-015', 'TPL-022'],
  }),
  defineField({
    key: 'authorization.requestWindowValue',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Request window',
    dataType: 'integer',
    control: 'number',
    normalization: 'INTEGER',
    comparison: 'NUMERIC_TOLERANCE',
    comparisonTolerance: 0,
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Auth request window',
    helpText:
      'How many days or months an authorization request may be made. The template asks how many days from DOS a request may be made (02 §4).',
    privacy: 'OPERATIONAL',
    traceIds: ['TPL-023'],
  }),
  defineField({
    key: 'authorization.requestWindowUnit',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Request window unit',
    dataType: 'categorical',
    control: 'select',
    options: WINDOW_UNIT_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Auth window unit',
    helpText: 'Calendar days, business days or months.',
    privacy: 'OPERATIONAL',
    traceIds: ['TPL-023'],
  }),
  defineField({
    key: 'authorization.requestWindowReference',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Request window measured from',
    dataType: 'categorical',
    control: 'select',
    options: WINDOW_REFERENCE_OPTIONS,
    normalization: 'CATEGORICAL',
    comparison: 'ALIAS',
    allowedSources: MASTER_ELIGIBLE_SOURCES,
    temporalClass: 'stable',
    exportColumn: 'Auth window reference',
    helpText:
      'The reference point the window counts from. A window before the date of service and one after it are materially different rules.',
    privacy: 'OPERATIONAL',
    traceIds: ['TPL-023'],
  }),
  defineField({
    key: 'authorization.number',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Authorization number',
    dataType: 'identifier',
    control: 'text',
    normalization: 'IDENTIFIER',
    comparison: 'IDENTIFIER_STRICT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Auth number',
    helpText: 'Issued authorization reference, with leading zeros preserved.',
    privacy: 'PHI_INDIRECT',
    traceIds: ['MTG-010', 'TPL-021'],
  }),
  defineField({
    key: 'authorization.coverageStartDate',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Authorization start date',
    dataType: 'date',
    control: 'date',
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Auth start',
    helpText: 'First date the authorization covers.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-021'],
  }),
  defineField({
    key: 'authorization.coverageEndDate',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Authorization end date',
    dataType: 'date',
    control: 'date',
    normalization: 'DATE',
    comparison: 'DATE_EXACT',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Auth end',
    helpText: 'Last date the authorization covers.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'TPL-021'],
  }),
  defineField({
    key: 'authorization.medicalNecessityReviewRequired',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.AUTHORIZATION,
    label: 'Medical-necessity review required',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Medical necessity review',
    helpText:
      'Whether the payer applies a separate medical-necessity review. This is a distinct authorization context from initial evaluation and treatment (08 §10).',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-021'],
  }),
  defineField({
    key: 'referral.required',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.REFERRAL,
    label: 'Referral required',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'Referral required',
    helpText: 'Whether a referral is needed. Never defaulted to No.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['MTG-010', 'CUR-004', 'TPL-024'],
  }),
  defineField({
    key: 'referral.pcpRequired',
    section: VobSection.VISITS_AUTHORIZATION,
    subgroup: VobSubgroup.REFERRAL,
    label: 'PCP referral required',
    dataType: 'categorical',
    control: 'select',
    options: ANSWER_OPTIONS,
    visibleRule: rule.neq('referral.required', 'NOT_APPLICABLE'),
    normalization: 'ANSWER',
    comparison: 'ALIAS',
    allowedSources: CALL_VERIFIABLE_SOURCES,
    temporalClass: 'dynamic',
    exportColumn: 'PCP referral required',
    helpText: 'Whether the referral must come from the primary care physician specifically.',
    privacy: 'PHI_BENEFIT',
    traceIds: ['TPL-024'],
  }),
];

export const VISITS_AUTHORIZATION_FIELDS: readonly FieldStructure[] = [
  ...VISIT_FIELDS,
  ...AUTHORIZATION_FIELDS,
];
